/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-configs-recommended.ts' */

export = {
  plugins: ["@tunnel/neverthrow"],
  rules: {
    "@tunnel/neverthrow/must-use-result": "error"
  },
};
